var availableCards = [
	"'I would be ungrateful if...'",
	"Member of the bishopric falls asleep",
	"The phrase 'Tender Mercies'",
	"Odd use of the word 'Even'",
	"Someone gets up after the meeting should end",
	"Mad dash for first place",
	"Child without parent",
	"Politics",
	"Name dropper",
	"'...With every fiber of my being...'",
	"The Arrangement ('I'll go up if you go up')",
	"Too much information",
	"'In the name of Thy Son...'",
	"Child with parent giving words",
	"Bad Joke (people don't laugh)",
	"The Regular",
	"Moment of Silence (over 30 seconds)",
	"Movie Comparison",
	"'On my mission...'",
	"The Ugly Cry",
	"The Long Talker (over ten minutes)",
	"Not a member of the ward",
	"Good Joke (people laugh)",
	"Travelogue",
	"Medical Problems",
	"Someone talks in a foreign language",
	"'I don't know where I would be...'",
	"'I don't know why I'm up here...'",
	"Three Nephites",
	"Entire testimony without mentioning Jesus",
	"Bruce R. McConkie Quote",
	"A child cries for 5 minutes"
];