var availableCards = [
	"Member of the bishopric falls asleep",
	"The phrase 'Tender Mercies'",
	"Odd use of the word 'Even'",
	"Politics or current events",
	"Name dropper",
	"'...With every fiber of my being...'",
	"Too much information",
	"'In the name of Thy Son...' (not in a prayer)",
	"Bad Joke (people don't laugh)",
	"Pop culture or sports reference",
	"'On my mission...'",
	"The speaker cries",
	"Good Joke (people laugh)",
	"Someone talks in a foreign language",
	"'I don't know where I would be...'",
	"Reference to outdated counsel (caffeine, etc.)",
	"A child cries for 5 minutes",
	"Random hymn nobody knows",
	"'This talk is more for me than for you'",
	"Speaker describes being asked to speak",
	"The organist hits a wrong note",
	"Audible phone ring",
	"Mention of the world getting more wicked",
	"'The dictionary defines...'",
	"Someone reads a poem",
	"Someone mentions leaders praying for members",
	"Speaker talks about love for their spouse",
	"Talk based on conference talk",
	"Mention of patriarchal blessing",
	"Reference to non-members as 'Gentiles'",
	"Runaway child",
	"Hymn sung or played very slowly",
	"Really long prayer",
	"'The family is under attack'",
	"The phrase 'The mission field'",
	"Humble brag",
	"Fancy prayer beginning or ending",
	"'For those of you who don't know me...'",
	"The prase 'Hasten the work'",
	"Sacrament Prayer re-do"
];