var availableCards = [
	"Member of the bishopric falls asleep",
	"The phrase 'Tender Mercies'",
	"Odd use of the word 'Even'",
	"Someone gets up after the meeting should end",
	"Three or more people waiting to speak",
	"Child without parent",
	"Politics or current events",
	"Name dropper",
	"'...With every fiber of my being...'",
	"Two People Go Up Together",
	"Over Sharing",
	"'In the name of Thy Son...' (not in a prayer)",
	"Child with parent giving words",
	"Bad Joke (people don't laugh)",
	"The Regular",
	"Moment of Silence (over 30 seconds)",
	"Pop Culture or Sports Reference",
	"'On my mission...'",
	"The speaker cries",
	"The Long Talker (over ten minutes)",
	"Not a member of the ward",
	"Good Joke (people laugh)",
	"Travel",
	"Medical Problems",
	"Someone talks in a foreign language",
	"'I don't know where I would be...'",
	"'I don't know why I'm up here...'",
	"Someone quotes scripture verbatim",
	"Someone reads a passage",
	"Entire testimony without mention of Jesus",
	"Reference to outdated counsel (caffeine, etc.)",
	"A child cries for 5 minutes",
	"'I'll be brief...' (then isn't brief)",
	"False doctrine",
	"'I'd like to bear my testimony' (exact wording)"
];
